export const getAllProductsConstant = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
};

export const addToCartConstant = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
};
export const removeCartItemConstant = {
  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
};
export const clearCartConstant = {
  CLEAR_CART_REQUEST: "CLEAR_CART_REQUEST",
  CLEAR_CART_SUCCESS: "CLEAR_CART_SUCCESS",
  CLEAR_CART_FAILURE: "CLEAR_CART_FAILURE",
};

export const getProductFromServerConstant ={
  GET_PRODUCT_FROM_SERVER_REQUEST :'GET_PRODUCT_FROM_SERVER_REQUEST',
  GET_PRODUCT_FROM_SERVER_SUCCESS :'GET_PRODUCT_FROM_SERVER_SUCCESS',
  GET_PRODUCT_FROM_SERVER_FAILURE :'GET_PRODUCT_FROM_SERVER_FAILURE'
}